import React from 'react';
import { render } from 'react-native-testing-library';
import ListItems from '../ListItems';

const item = {"id":22887,"url":"https:\/\/yts.mx\/movies\/nurse-3d-2013","imdb_code":"tt1913166","title":"Nurse 3D","title_english":"Nurse 3D","title_long":"Nurse 3D (2013)","slug":"nurse-3d-2013","year":2013,"rating":4.5,"runtime":84,"genres":["Horror","Thriller"],"summary":"By day Abby Russell is a dedicated nurse, someone you wouldn't hesitate to trust your life with. But by night, her real work begins...using her smoldering sexuality she lures cheating men to their brutal deaths and exposes them for who they really are. When a younger nurse starts to suspect Abby's actions and compromises her master plan, Abby must find a way to outsmart her long enough to bring the cheater you'd least expect to justice.","description_full":"By day Abby Russell is a dedicated nurse, someone you wouldn't hesitate to trust your life with. But by night, her real work begins...using her smoldering sexuality she lures cheating men to their brutal deaths and exposes them for who they really are. When a younger nurse starts to suspect Abby's actions and compromises her master plan, Abby must find a way to outsmart her long enough to bring the cheater you'd least expect to justice.","synopsis":"By day Abby Russell is a dedicated nurse, someone you wouldn't hesitate to trust your life with. But by night, her real work begins...using her smoldering sexuality she lures cheating men to their brutal deaths and exposes them for who they really are. When a younger nurse starts to suspect Abby's actions and compromises her master plan, Abby must find a way to outsmart her long enough to bring the cheater you'd least expect to justice.","yt_trailer_code":"ipdZPDiTLME","language":"en","mpa_rating":"R","background_image":"https:\/\/yts.mx\/assets\/images\/movies\/nurse_3d_2013\/background.jpg","background_image_original":"https:\/\/yts.mx\/assets\/images\/movies\/nurse_3d_2013\/background.jpg","small_cover_image":"https:\/\/yts.mx\/assets\/images\/movies\/nurse_3d_2013\/small-cover.jpg","medium_cover_image":"https:\/\/yts.mx\/assets\/images\/movies\/nurse_3d_2013\/medium-cover.jpg","large_cover_image":"https:\/\/yts.mx\/assets\/images\/movies\/nurse_3d_2013\/large-cover.jpg","state":"ok","torrents":[{"url":"https:\/\/yts.mx\/torrent\/download\/63D5A6C3B708F583A21A65D219935EF8E79992D3","hash":"63D5A6C3B708F583A21A65D219935EF8E79992D3","quality":"3D","type":"bluray","seeds":33,"peers":8,"size":"1.55 GB","size_bytes":1664299827,"date_uploaded":"2020-10-28 04:22:18","date_uploaded_unix":1603855338}]}

test('it renders all inputs as expected', ()=> {
    const { toJSON } = render(<ListItems data={item}/>);

    expect(toJSON()).toMatchSnapshot();
})